/**
 * Daylight design tokens — the single source of truth.
 * Components never use these values directly: they use the CSS variables
 * generated by cssVars.ts (e.g. var(--dl-color-text-secondary)).
 * Token names match the Daylight spec and the Figma styles.
 */

export const primitives = {
  neutral: {
    0: '#FFFFFF',
    50: '#F7F7F4',
    100: '#EFEFEA',
    150: '#ECECE6',
    200: '#E3E3DC',
    300: '#C9C9C2',
    500: '#8D8E95',
    600: '#6E7079',
    700: '#62646C',
    900: '#15161A',
  },
  cobalt: { 50: '#EAF0FF', 500: '#2E5BFF', 600: '#2449D6' },
  protein: { 50: '#FFEDE8', 400: '#FF8A73', 800: '#A8341C' },
  carbs: { 50: '#FFF5D6', 400: '#F5C23E', 800: '#7A5600' },
  fat: { 50: '#E6F1FF', 400: '#6FB1FF', 800: '#1D56A3' },
  danger: { 50: '#FDECEC', 700: '#B42318' },
} as const;

const p = primitives;

export const color = {
  bg: {
    canvas: p.neutral[50],
    surface: p.neutral[0],
    subtle: p.neutral[100],
    inset: p.neutral[150],
  },
  border: {
    hairline: p.neutral[150],
    field: p.neutral[200],
    strong: p.neutral[300],
  },
  text: {
    primary: p.neutral[900],
    secondary: p.neutral[700],
    placeholder: p.neutral[600],
    disabled: p.neutral[500],
    onAccent: p.neutral[0],
  },
  accent: {
    default: p.cobalt[500],
    pressed: p.cobalt[600],
    subtle: p.cobalt[50],
  },
  macro: {
    protein: { fill: p.protein[400], surface: p.protein[50], text: p.protein[800] },
    carbs: { fill: p.carbs[400], surface: p.carbs[50], text: p.carbs[800] },
    fat: { fill: p.fat[400], surface: p.fat[50], text: p.fat[800] },
  },
  danger: { text: p.danger[700], surface: p.danger[50] },
  overlay: {
    scrim: 'rgba(21, 22, 26, 0.36)',
    photoFrom: 'rgba(20, 16, 12, 0)',
    photoTo: 'rgba(20, 16, 12, 0.72)',
  },
} as const;

/** 4 px grid. */
export const space = { 1: 4, 2: 8, 3: 12, 4: 16, 5: 20, 6: 24, 8: 32, 10: 40 } as const;

export const size = {
  touchMin: 44,
  buttonLg: 52,
  buttonMd: 44,
  field: 48,
  chip: 36,
  iconButton: 40,
  key: 44,
  tag: 24,
  icon: { sm: 16, md: 20, lg: 24 },
  screenMargin: 20,
  contentMax: 560,
} as const;

export const radius = { sm: 12, md: 16, lg: 20, xl: 28, full: 999 } as const;

export const elevation = {
  e0: 'none',
  e1: '0 1px 2px rgba(21, 22, 26, 0.04), 0 8px 24px rgba(21, 22, 26, 0.05)',
  e2: '0 8px 24px rgba(21, 22, 26, 0.10)',
  e2Up: '0 -8px 24px rgba(21, 22, 26, 0.06)',
} as const;

export const focus = { width: 2, offset: 2, color: color.accent.default } as const;

export const motion = { fast: '150ms', base: '200ms', slow: '250ms', ease: 'cubic-bezier(0.2, 0, 0, 1)' } as const;

export const tokens = { primitives, color, space, size, radius, elevation, focus, motion } as const;
export type Tokens = typeof tokens;
